// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type MessagePayload = cpex::plugin::types::MessagePayload;
pub type Extensions = cpex::plugin::types::Extensions;
pub type PluginResult = cpex::plugin::types::PluginResult;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_handle_hook_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: i32,
    arg3: *mut u8,
    arg4: usize,
    arg5: i32,
    arg6: *mut u8,
    arg7: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result3 = T::handle_hook(
        cpex::plugin::types::MessagePayload {
            data: _rt::string_lift(bytes0),
        },
        cpex::plugin::types::Extensions {
            security: match arg2 {
                0 => None,
                1 => {
                    let e = {
                        let len1 = arg4;
                        let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
                        _rt::string_lift(bytes1)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            http: match arg5 {
                0 => None,
                1 => {
                    let e = {
                        let len2 = arg7;
                        let bytes2 = _rt::Vec::from_raw_parts(arg6.cast(), len2, len2);
                        _rt::string_lift(bytes2)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
        },
    );
    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
    use cpex::plugin::types::PluginResult as V6;
    match result3 {
        V6::Allow => {
            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
        }
        V6::Deny(e) => {
            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
            let vec5 = (e.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *ptr4.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5
                .cast_mut();
        }
    }
    ptr4
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_handle_hook<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
pub trait Guest {
    fn handle_hook(payload: MessagePayload, extensions: Extensions) -> PluginResult;
}
#[doc(hidden)]
macro_rules! __export_world_plugin_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "handle-hook")] unsafe extern "C" fn
        export_handle_hook(arg0 : * mut u8, arg1 : usize, arg2 : i32, arg3 : * mut u8,
        arg4 : usize, arg5 : i32, arg6 : * mut u8, arg7 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_handle_hook_cabi::<$ty > (arg0, arg1, arg2, arg3,
        arg4, arg5, arg6, arg7) } } #[unsafe (export_name = "cabi_post_handle-hook")]
        unsafe extern "C" fn _post_return_handle_hook(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_handle_hook::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_plugin_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 3 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod cpex {
    pub mod plugin {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct MessagePayload {
                pub data: _rt::String,
            }
            impl ::core::fmt::Debug for MessagePayload {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("MessagePayload").field("data", &self.data).finish()
                }
            }
            #[derive(Clone)]
            pub struct Extensions {
                pub security: Option<_rt::String>,
                pub http: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for Extensions {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Extensions")
                        .field("security", &self.security)
                        .field("http", &self.http)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum PluginResult {
                Allow,
                Deny(_rt::String),
            }
            impl ::core::fmt::Debug for PluginResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        PluginResult::Allow => {
                            f.debug_tuple("PluginResult::Allow").finish()
                        }
                        PluginResult::Deny(e) => {
                            f.debug_tuple("PluginResult::Deny").field(e).finish()
                        }
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_plugin_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:cpex:plugin:plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 473] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xdc\x02\x01A\x02\x01\
A\x0a\x01B\x09\x01r\x02\x04names\x07versions\x04\0\x0dplugin-config\x03\0\0\x01r\
\x01\x04datas\x04\0\x0fmessage-payload\x03\0\x02\x01ks\x01r\x02\x08security\x04\x04\
http\x04\x04\0\x0aextensions\x03\0\x05\x01q\x02\x05allow\0\0\x04deny\x01s\0\x04\0\
\x0dplugin-result\x03\0\x07\x03\0\x11cpex:plugin/types\x05\0\x02\x03\0\0\x0fmess\
age-payload\x03\0\x0fmessage-payload\x03\0\x01\x02\x03\0\0\x0aextensions\x03\0\x0a\
extensions\x03\0\x03\x02\x03\0\0\x0dplugin-result\x03\0\x0dplugin-result\x03\0\x05\
\x01@\x02\x07payload\x02\x0aextensions\x04\0\x06\x04\0\x0bhandle-hook\x01\x07\x04\
\0\x12cpex:plugin/plugin\x04\0\x0b\x0c\x01\0\x06plugin\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
