plugin:
  name: "samplePlugin"
  sandbox:
    type: "wasm"
    wasm_version: "p2"
    policy:
      dir_name: ["./data"]
      permissions:
        dir: ["read"] # or mutate
        file: ["read"] # or write