// Location: ./crates/cpex-wasm-plugin/src/examples/net_test.rs
// Copyright 2026
// SPDX-License-Identifier: Apache-2.0
// Authors: Shriti Priya

#![cfg(feature = "net-test")]

use async_trait::async_trait;

use cpex_core::cmf::{CmfHook, MessagePayload};
use cpex_core::context::PluginContext;
use cpex_core::error::PluginError;
use cpex_core::extensions::container::Extensions;
use cpex_core::hooks::trait_def::{HookHandler, PluginResult};
use cpex_core::plugin::{Plugin, PluginConfig};

use crate::cpex_log;

pub struct NetTestPlugin;

impl Default for NetTestPlugin {
    fn default() -> Self {
        Self
    }
}

static PLUGIN_CONFIG: std::sync::OnceLock<PluginConfig> = std::sync::OnceLock::new();

#[async_trait]
impl Plugin for NetTestPlugin {
    fn config(&self) -> &PluginConfig {
        PLUGIN_CONFIG.get_or_init(|| PluginConfig {
            name: "net-test".to_string(),
            kind: "wasm://net-test.wasm".to_string(),
            hooks: vec!["cmf.tool_pre_invoke".to_string()],
            ..Default::default()
        })
    }

    async fn initialize(&self) -> Result<(), Box<PluginError>> {
        Ok(())
    }

    async fn shutdown(&self) -> Result<(), Box<PluginError>> {
        Ok(())
    }
}

impl HookHandler<CmfHook> for NetTestPlugin {
    async fn handle(
        &self,
        _payload: &MessagePayload,
        _extensions: &Extensions,
        ctx: &mut PluginContext,
    ) -> PluginResult<MessagePayload> {
        cpex_log!(info, "attempting outbound HTTP to httpbin.org");

        // Attempt an outbound HTTP request using WASI HTTP
        // This uses the raw WASI HTTP types generated by wit-bindgen
        // In WASM, we can't use reqwest — we use the WASI outgoing-handler directly
        // For simplicity, we just report whether the std::net path is available
        // (it won't be in WASM — WASI doesn't expose raw sockets via std::net)
        //
        // The real network test is at the host level: the NetworkPolicy hook
        // intercepts outgoing HTTP requests and denies them if not in the allowlist.
        // We test this by checking if the environment suggests network is blocked.

        // Try to resolve a DNS name (tests if network stack is available at all)
        match std::net::ToSocketAddrs::to_socket_addrs(&("httpbin.org", 80)) {
            Ok(_addrs) => {
                ctx.set_local("net_access", serde_json::json!("dns_resolved"));
                cpex_log!(warn, "DNS resolution succeeded — unexpected in sandboxed WASM");
            }
            Err(e) => {
                ctx.set_local("net_access", serde_json::json!("denied"));
                ctx.set_local("net_error", serde_json::json!(e.to_string()));
                cpex_log!(info, "network access denied: {}", e);
            }
        }

        PluginResult::allow()
    }
}
