package cpex:plugin;

interface types {
  record plugin-config {
    name: string,
    version: string,
  }
  
  record message-payload {
    data: string,
  }
  
  record extensions {
    security: option<string>,
    http: option<string>,
  }
  
  variant plugin-result {
    allow,
    deny(string),
  }
}

world plugin {
  import wasi:io/poll@0.2.6;
  import wasi:io/error@0.2.6;
  import wasi:io/streams@0.2.6;
  import wasi:clocks/monotonic-clock@0.2.6;
  import wasi:http/types@0.2.6;
  import wasi:http/outgoing-handler@0.2.6;

  use types.{message-payload, extensions, plugin-result};

  export handle-hook: func(
    payload: message-payload,
    extensions: extensions
  ) -> plugin-result;
}

